version: "3.8"

services:
  # PostgreSQL for development
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: tstack_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d tstack_dev"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_dev_data:

# Usage:
# Start PostgreSQL: docker-compose -f docker-compose.dev.yml up -d
# Stop: docker-compose -f docker-compose.dev.yml down
# Reset data: docker-compose -f docker-compose.dev.yml down -v
