import type { EntityNames } from "../../utils/stringUtils.ts";

export function generateEntityConfigTemplate(names: EntityNames): string {
  return `/**
 * ${names.pascalSingular} Entity Configuration
 * Generated by tstack scaffold
 * 
 * TODO: Customize this configuration to match your entity's fields
 */

import type { EntityConfig } from "@/lib/admin/types.ts";
import type { ${names.pascalSingular} } from "@/entities/${names.snakePlural}/${names.kebabSingular}.types.ts";
import { ${names.singular}Service } from "@/entities/${names.snakePlural}/${names.kebabSingular}.service.ts";

export const ${names.singular}Config: EntityConfig<${names.pascalSingular}> = {
  // Basic info
  name: "${names.snakePlural}",
  singularName: "${names.pascalSingular}",
  pluralName: "${names.pascalPlural}",
  apiPath: "/ts-admin/${names.kebabPlural}",
  idField: "id",

  // UI customization
  displayField: "id", // TODO: Change to your main field (e.g., "title", "name")
  descriptionField: undefined, // TODO: Optional subtitle field (e.g., "slug", "email")

  // Service
  service: ${names.singular}Service,

  // Fields configuration
  // TODO: Add your entity fields here to match ${names.kebabSingular}.model.ts
  fields: [
    {
      name: "id",
      label: "ID",
      type: "number",
      showInList: true,
      showInShow: true,
      showInForm: false,
      sortable: true,
    },
    // TODO: Add your custom fields here
    // Example:
    // {
    //   name: "title",
    //   label: "Title",
    //   type: "string",
    //   required: true,
    //   showInList: true,
    //   showInShow: true,
    //   showInForm: true,
    //   sortable: true,
    //   searchable: true,
    //   placeholder: "Enter title",
    // },
    {
      name: "createdAt",
      label: "Created At",
      type: "datetime",
      showInList: false,
      showInShow: true,
      showInForm: false,
    },
    {
      name: "updatedAt",
      label: "Updated At",
      type: "datetime",
      showInList: false,
      showInShow: true,
      showInForm: false,
    },
  ],

  // Permissions
  canCreate: true,
  canEdit: true,
  canDelete: true,
  canView: true,
};
`;
}
