import type { EntityNames } from "../../utils/stringUtils.ts";

export function generateEntityServiceTemplate(names: EntityNames): string {
  return `/**
 * ${names.pascalSingular} Service
 * Generated by tstack scaffold
 * Extends BaseService for standard CRUD operations
 */

import { BaseService } from "@/lib/base-service.ts";
import type { ${names.pascalSingular} } from "./${names.kebabSingular}.types.ts";

export class ${names.pascalSingular}Service extends BaseService<${names.pascalSingular}> {
  constructor() {
    super("/ts-admin/${names.snakePlural}");
  }

  // Add custom methods here if needed
  // Example:
  // async customMethod(id: number): Promise<SomeType> {
  //   return this.client.post<SomeType>(\`\${this.basePath}/\${id}/custom\`, {});
  // }
}

export const ${names.singular}Service = new ${names.pascalSingular}Service();
`;
}
