import type { EntityNames } from "../../utils/stringUtils.ts";

export function generateEntityTypesTemplate(names: EntityNames): string {
  return `/**
 * ${names.pascalSingular} TypeScript types
 * Generated by tstack scaffold
 * 
 * TODO: Update these types to match your backend model
 */

export interface ${names.pascalSingular} extends Record<string, unknown> {
  id: number;
  // TODO: Add your entity fields here
  // Example:
  // name: string;
  // description?: string | null;
  // isActive: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface Create${names.pascalSingular}Input {
  // TODO: Add fields for creating a ${names.singular}
  // Example:
  // name: string;
  // description?: string | null;
  // isActive?: boolean;
}

export interface Update${names.pascalSingular}Input {
  // TODO: Add fields for updating a ${names.singular}
  // Example:
  // name?: string;
  // description?: string | null;
  // isActive?: boolean;
}

export interface ${names.pascalSingular}ListResponse {
  success: boolean;
  data: ${names.pascalSingular}[];
  pagination: {
    page: number;
    pageSize: number;
    total: number;
    totalPages: number;
  };
}

export interface ${names.pascalSingular}Response {
  success: boolean;
  data: ${names.pascalSingular};
}

export interface Delete${names.pascalSingular}Response {
  success: boolean;
  message: string;
}
`;
}
