/**
 * Cleanup script for starter test database
 * - Drops the test database after tests complete
 * - Only removes migrations if they were auto-generated by test setup
 */

import "@std/dotenv/load";

const dbName = "tstack_starter_test";
const MIGRATIONS_GENERATED_FLAG = ".migrations_generated_by_test";

// Step 1: Drop test database
try {
  const cmd = new Deno.Command("psql", {
    args: [
      "-U",
      "postgres",
      "-h",
      "localhost",
      "-c",
      `DROP DATABASE IF EXISTS ${dbName}`,
    ],
    env: { PGPASSWORD: "password" },
    stdout: "piped",
    stderr: "piped",
  });

  const { success } = await cmd.output();
  if (success) {
    console.log(`[CLEANUP] Database "${dbName}" dropped`);
  }
} catch (error) {
  console.error(`[WARNING] Could not drop database: ${error}`);
}

// Step 2: Only clean up migrations if they were auto-generated by test setup
try {
  // Check if test setup generated the migrations
  await Deno.stat(MIGRATIONS_GENERATED_FLAG);
  
  // Flag exists - migrations were auto-generated, clean them up
  const migrationsDir = "./migrations";
  const metaDir = "./migrations/meta";

  // Remove .sql files
  for await (const entry of Deno.readDir(migrationsDir)) {
    if (entry.isFile && entry.name.endsWith(".sql")) {
      await Deno.remove(`${migrationsDir}/${entry.name}`);
    }
  }

  // Remove entire meta/ directory
  try {
    await Deno.remove(metaDir, { recursive: true });
  } catch {
    // meta dir might not exist
  }

  // Remove the flag file
  await Deno.remove(MIGRATIONS_GENERATED_FLAG);
  
  console.log("[CLEANUP] Auto-generated migration files removed");
} catch {
  // Flag doesn't exist - migrations were created by developer, leave them alone
}
