/**
 * Cleanup script for starter test database
 * - Drops the test database after tests complete
 * - Only removes migrations if they were auto-generated by test setup
 */

import { loadSync } from "@std/dotenv";

// Load test environment (same order as setup-test-full.ts)
try {
  loadSync({ envPath: ".env.test.local", export: true });
} catch {
  try {
    loadSync({ envPath: ".env.test", export: true });
  } catch {
    // No env file found, rely on system environment variables
  }
}

const dbName = "tstack_starter_test";
const MIGRATIONS_GENERATED_FLAG = ".migrations_generated_by_test";

// Extract credentials from DATABASE_URL when available, otherwise PGUSER/PGPASSWORD
let dbUser = Deno.env.get("PGUSER") || "postgres";
let dbPassword = Deno.env.get("PGPASSWORD") || "password";
const databaseUrl = Deno.env.get("DATABASE_URL");
if (databaseUrl) {
  try {
    const url = new URL(databaseUrl);
    if (url.username) dbUser = url.username;
    if (url.password) dbPassword = url.password;
  } catch {
    // Invalid URL, use PGUSER/PGPASSWORD fallbacks
  }
}

// Step 1: Drop test database
try {
  const cmd = new Deno.Command("psql", {
    args: [
      "-U",
      dbUser,
      "-h",
      "localhost",
      "-d",
      "postgres",
      "-c",
      `DROP DATABASE IF EXISTS ${dbName}`,
    ],
    env: { PGPASSWORD: dbPassword },
    stdout: "piped",
    stderr: "piped",
  });

  const { success } = await cmd.output();
  if (success) {
    console.log(`[CLEANUP] Database "${dbName}" dropped`);
  }
} catch (error) {
  console.error(`[WARNING] Could not drop database: ${error}`);
}

// Step 2: Only clean up migrations if they were auto-generated by test setup
try {
  // Check if test setup generated the migrations
  await Deno.stat(MIGRATIONS_GENERATED_FLAG);

  // Flag exists - migrations were auto-generated, clean them up
  const migrationsDir = "./migrations";
  const metaDir = "./migrations/meta";

  // Remove .sql files
  for await (const entry of Deno.readDir(migrationsDir)) {
    if (entry.isFile && entry.name.endsWith(".sql")) {
      await Deno.remove(`${migrationsDir}/${entry.name}`);
    }
  }

  // Remove entire meta/ directory
  try {
    await Deno.remove(metaDir, { recursive: true });
  } catch {
    // meta dir might not exist
  }

  // Remove the flag file
  await Deno.remove(MIGRATIONS_GENERATED_FLAG);

  console.log("[CLEANUP] Auto-generated migration files removed");
} catch {
  // Flag doesn't exist - migrations were created by developer, leave them alone
}
